[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
betting_contract = "9XiAk8AJVCWkypFstaRERag2DeKgtSergJR4PqTYeV9C"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.mainnet-beta.solana.com"
wallet = "/home/jong/.config/solana/bitbet-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"